<?php
/**
 * Pattern "Comparison table" from the Casino Guide kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Comparison table', 'page-builder-sandwich' ),
		__( 'Casino Guide', 'page-builder-sandwich' )
	),
	'keywords' => array( 'igaming', 'comparison' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#1a1d33"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1a1d33;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:pbs/comparison-table {"caption":"@@PBS_T2@@","columns":[{"title":"@@PBS_T3@@","highlight":true},{"title":"@@PBS_T4@@"},{"title":"@@PBS_T5@@"}],"rows":[{"label":"@@PBS_T6@@","cells":[{"type":"text","text":"@@PBS_T7@@"},{"type":"text","text":"@@PBS_T8@@"},{"type":"text","text":"@@PBS_T9@@"}]},{"label":"@@PBS_T10@@","cells":[{"type":"text","text":"@@PBS_T11@@"},{"type":"text","text":"@@PBS_T12@@"},{"type":"text","text":"@@PBS_T13@@"}]},{"label":"@@PBS_T14@@","cells":[{"type":"yes"},{"type":"yes"},{"type":"no"}]},{"label":"@@PBS_T15@@","cells":[{"type":"yes"},{"type":"no"},{"type":"yes"}]},{"label":"@@PBS_T16@@","cells":[{"type":"yes"},{"type":"yes"},{"type":"yes"}]}]} -->
<table><caption>@@PBS_T2@@</caption><thead><tr><td></td><th scope="col">@@PBS_T3@@</th><th scope="col">@@PBS_T4@@</th><th scope="col">@@PBS_T5@@</th></tr></thead><tbody><tr><th scope="row">@@PBS_T6@@</th><td>@@PBS_T7@@</td><td>@@PBS_T8@@</td><td>@@PBS_T9@@</td></tr><tr><th scope="row">@@PBS_T10@@</th><td>@@PBS_T11@@</td><td>@@PBS_T12@@</td><td>@@PBS_T13@@</td></tr><tr><th scope="row">@@PBS_T14@@</th><td>✓</td><td>✓</td><td>✗</td></tr><tr><th scope="row">@@PBS_T15@@</th><td>✓</td><td>✗</td><td>✓</td></tr><tr><th scope="row">@@PBS_T16@@</th><td>✓</td><td>✓</td><td>✓</td></tr></tbody></table>
<!-- /wp:pbs/comparison-table -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">@@PBS_T17@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->',
		array(
			__( 'This month\'s top-rated casinos', 'page-builder-sandwich' ),
			__( 'Scores come from our own tests. Bonuses change often, so always read the terms on the casino\'s site.', 'page-builder-sandwich' ),
			__( 'Top-rated casinos compared', 'page-builder-sandwich' ),
			__( 'Royal Harbour', 'page-builder-sandwich' ),
			__( 'Lucky Meadow', 'page-builder-sandwich' ),
			__( 'Star Lantern', 'page-builder-sandwich' ),
			__( 'Our score', 'page-builder-sandwich' ),
			__( '9.4 / 10', 'page-builder-sandwich' ),
			__( '9.1 / 10', 'page-builder-sandwich' ),
			__( '8.8 / 10', 'page-builder-sandwich' ),
			__( 'Welcome offer', 'page-builder-sandwich' ),
			__( '100% up to 200', 'page-builder-sandwich' ),
			__( '50 free spins', 'page-builder-sandwich' ),
			__( '150% up to 100', 'page-builder-sandwich' ),
			__( 'Fast withdrawals', 'page-builder-sandwich' ),
			__( 'Live dealer games', 'page-builder-sandwich' ),
			__( 'Deposit limits', 'page-builder-sandwich' ),
			__( '18+ only. Offers are subject to the operator\'s terms and your country\'s rules.', 'page-builder-sandwich' ),
		)
	),
);
