<?php
/**
 * Pattern "Features" from the Casino Guide kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Features', 'page-builder-sandwich' ),
		__( 'Casino Guide', 'page-builder-sandwich' )
	),
	'keywords' => array( 'igaming', 'features' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#1a1d33"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1a1d33;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:pbs/feature-list {"items":[{"title":"@@PBS_T2@@","text":"@@PBS_T3@@"},{"title":"@@PBS_T4@@","text":"@@PBS_T5@@"},{"title":"@@PBS_T6@@","text":"@@PBS_T7@@"},{"title":"@@PBS_T8@@","text":"@@PBS_T9@@"},{"title":"@@PBS_T10@@","text":"@@PBS_T11@@"},{"title":"@@PBS_T12@@","text":"@@PBS_T13@@"}],"level":3} -->
<ul><li><h3>@@PBS_T2@@</h3><p>@@PBS_T3@@</p></li><li><h3>@@PBS_T4@@</h3><p>@@PBS_T5@@</p></li><li><h3>@@PBS_T6@@</h3><p>@@PBS_T7@@</p></li><li><h3>@@PBS_T8@@</h3><p>@@PBS_T9@@</p></li><li><h3>@@PBS_T10@@</h3><p>@@PBS_T11@@</p></li><li><h3>@@PBS_T12@@</h3><p>@@PBS_T13@@</p></li></ul>
<!-- /wp:pbs/feature-list --></div>
<!-- /wp:group -->',
		array(
			__( 'How we review a casino', 'page-builder-sandwich' ),
			__( 'Every review follows the same checklist, so scores can be compared fairly.', 'page-builder-sandwich' ),
			__( 'Licence and safety', 'page-builder-sandwich' ),
			__( 'We confirm the licence with the regulator and check how player funds are protected.', 'page-builder-sandwich' ),
			__( 'Payouts', 'page-builder-sandwich' ),
			__( 'We deposit and withdraw with real money and time how long each payout takes.', 'page-builder-sandwich' ),
			__( 'Bonus terms', 'page-builder-sandwich' ),
			__( 'We read the wagering rules, caps and time limits so you do not have to.', 'page-builder-sandwich' ),
			__( 'Games', 'page-builder-sandwich' ),
			__( 'We look at the game studios, live tables and published return-to-player figures.', 'page-builder-sandwich' ),
			__( 'Support', 'page-builder-sandwich' ),
			__( 'We contact support by chat and email and rate the speed and the answers.', 'page-builder-sandwich' ),
			__( 'Responsible play', 'page-builder-sandwich' ),
			__( 'We check for deposit limits, reality checks, cool-off periods and self-exclusion.', 'page-builder-sandwich' ),
		)
	),
);
