<?php
/**
 * Pattern "Questions and answers" from the Casino Guide kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Questions and answers', 'page-builder-sandwich' ),
		__( 'Casino Guide', 'page-builder-sandwich' )
	),
	'keywords' => array( 'igaming', 'faq' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#1a1d33"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1a1d33;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:pbs/accordion {"single":true,"faq":true} -->
<div><!-- wp:pbs/accordion-item {"title":"@@PBS_T1@@","open":true} -->
<details open><summary>@@PBS_T1@@</summary><!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T3@@"} -->
<details><summary>@@PBS_T3@@</summary><!-- wp:paragraph -->
<p>@@PBS_T4@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T5@@"} -->
<details><summary>@@PBS_T5@@</summary><!-- wp:paragraph -->
<p>@@PBS_T6@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item --></div>
<!-- /wp:pbs/accordion --></div>
<!-- /wp:group -->',
		array(
			__( 'Common questions', 'page-builder-sandwich' ),
			__( 'Are online casinos legal where I live?', 'page-builder-sandwich' ),
			__( 'It depends on your country and sometimes your region. Only play at casinos licensed for your location, and check the local rules first.', 'page-builder-sandwich' ),
			__( 'How do you make money?', 'page-builder-sandwich' ),
			__( 'Through affiliate commissions when readers sign up through our links. Rankings are decided by our tests before any commercial discussion.', 'page-builder-sandwich' ),
			__( 'What is a wagering requirement?', 'page-builder-sandwich' ),
			__( 'The number of times you must bet a bonus before you can withdraw winnings from it. Lower is better.', 'page-builder-sandwich' ),
		)
	),
);
