<?php
/**
 * Pattern "Questions and answers" from the Dental Clinic kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Questions and answers', 'page-builder-sandwich' ),
		__( 'Dental Clinic', 'page-builder-sandwich' )
	),
	'keywords' => array( 'medical', 'faq' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#0f3b3a"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0f3b3a;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:pbs/accordion {"single":true,"faq":true} -->
<div><!-- wp:pbs/accordion-item {"title":"@@PBS_T1@@","open":true} -->
<details open><summary>@@PBS_T1@@</summary><!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T3@@"} -->
<details><summary>@@PBS_T3@@</summary><!-- wp:paragraph -->
<p>@@PBS_T4@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T5@@"} -->
<details><summary>@@PBS_T5@@</summary><!-- wp:paragraph -->
<p>@@PBS_T6@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item --></div>
<!-- /wp:pbs/accordion --></div>
<!-- /wp:group -->',
		array(
			__( 'Frequently asked questions', 'page-builder-sandwich' ),
			__( 'Are you taking new patients?', 'page-builder-sandwich' ),
			__( 'Yes. You can book your first visit online.', 'page-builder-sandwich' ),
			__( 'Do you offer payment plans?', 'page-builder-sandwich' ),
			__( 'Yes, interest-free plans are available for larger treatments.', 'page-builder-sandwich' ),
			__( 'What if I am nervous?', 'page-builder-sandwich' ),
			__( 'Tell us when you book. We will take things at your pace.', 'page-builder-sandwich' ),
		)
	),
);
