<?php
/**
 * Pattern "Hero" from the Dental Clinic kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Hero', 'page-builder-sandwich' ),
		__( 'Dental Clinic', 'page-builder-sandwich' )
	),
	'keywords' => array( 'medical', 'hero' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ecf8f6","text":"#0f3b3a"},"spacing":{"padding":{"top":"112px","bottom":"112px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0f3b3a;background-color:#ecf8f6;padding-top:112px;padding-right:24px;padding-bottom:112px;padding-left:24px"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"58%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:58%"><!-- wp:paragraph {"fontSize":"small","style":{"typography":{"textTransform":"uppercase","letterSpacing":"2px"},"color":{"text":"#6fb7ff"}}} -->
<p class="has-text-color has-small-font-size" style="color:#6fb7ff;letter-spacing:2px;text-transform:uppercase">@@PBS_T0@@</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">@@PBS_T1@@</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"large"} -->
<p class="has-large-font-size">@@PBS_T2@@</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"left"}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#1a9e8f","text":"#ffffff"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background wp-element-button" href="/contact/" style="color:#ffffff;background-color:#1a9e8f">@@PBS_T3@@</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"#0f3b3a"}}} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color wp-element-button" href="/services/" style="color:#0f3b3a">@@PBS_T4@@</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"42%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:42%"><!-- wp:group {"style":{"color":{"background":"#ffffff","text":"#0f3b3a"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f3b3a;background-color:#ffffff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T5@@</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>@@PBS_T6@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T7@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T8@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T9@@</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'Accepting new patients', 'page-builder-sandwich' ),
			__( 'Gentle dental care for the whole family', 'page-builder-sandwich' ),
			__( 'Check-ups, hygiene, whitening and implants in a calm, modern clinic. Nervous patients are always welcome.', 'page-builder-sandwich' ),
			__( 'Book an appointment', 'page-builder-sandwich' ),
			__( 'Our treatments', 'page-builder-sandwich' ),
			__( 'Visiting us', 'page-builder-sandwich' ),
			__( 'Evening and Saturday appointments', 'page-builder-sandwich' ),
			__( 'Clear prices before treatment', 'page-builder-sandwich' ),
			__( 'Payment plans available', 'page-builder-sandwich' ),
			__( 'Emergency slots every day', 'page-builder-sandwich' ),
		)
	),
);
