<?php
/**
 * Pattern "Testimonials" from the Digital Agency kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Testimonials', 'page-builder-sandwich' ),
		__( 'Digital Agency', 'page-builder-sandwich' )
	),
	'keywords' => array( 'agency', 'testimonials' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#101014;background-color:#f5f5f7;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T1@@","name":"@@PBS_T2@@","role":"@@PBS_T3@@","rating":5} -->
<figure><blockquote><p>@@PBS_T1@@</p></blockquote><figcaption>@@PBS_T2@@, @@PBS_T3@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T4@@","name":"@@PBS_T5@@","role":"@@PBS_T6@@","rating":5} -->
<figure><blockquote><p>@@PBS_T4@@</p></blockquote><figcaption>@@PBS_T5@@, @@PBS_T6@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'What our clients say', 'page-builder-sandwich' ),
			__( 'They understood our business better than we did. Sales doubled in six months.', 'page-builder-sandwich' ),
			__( 'Chloe', 'page-builder-sandwich' ),
			__( 'Founder', 'page-builder-sandwich' ),
			__( 'Brilliant to work with: fast, honest and very talented.', 'page-builder-sandwich' ),
			__( 'Omar', 'page-builder-sandwich' ),
			__( 'Marketing director', 'page-builder-sandwich' ),
		)
	),
);
