<?php
/**
 * Pattern "Services" from the Digital Agency kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Services', 'page-builder-sandwich' ),
		__( 'Digital Agency', 'page-builder-sandwich' )
	),
	'keywords' => array( 'agency', 'services' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#101014"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#101014;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T1@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T3@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T4@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T5@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T6@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T7@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T8@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T9@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T10@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f5f5f7","text":"#101014"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#101014;background-color:#f5f5f7;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T11@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T12@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'What we do', 'page-builder-sandwich' ),
			__( 'Brand identity', 'page-builder-sandwich' ),
			__( 'Names, logos and visual systems that stand out.', 'page-builder-sandwich' ),
			__( 'Web design and build', 'page-builder-sandwich' ),
			__( 'Fast, accessible websites built to convert.', 'page-builder-sandwich' ),
			__( 'E-commerce', 'page-builder-sandwich' ),
			__( 'Online stores that are easy to run and easy to buy from.', 'page-builder-sandwich' ),
			__( 'SEO and content', 'page-builder-sandwich' ),
			__( 'Search strategy and content that earns traffic.', 'page-builder-sandwich' ),
			__( 'Paid media', 'page-builder-sandwich' ),
			__( 'Search and social campaigns measured by results.', 'page-builder-sandwich' ),
			__( 'Care plans', 'page-builder-sandwich' ),
			__( 'Updates, security and improvements every month.', 'page-builder-sandwich' ),
		)
	),
);
