<?php
/**
 * Pattern "Testimonials" from the Fitness Gym kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Testimonials', 'page-builder-sandwich' ),
		__( 'Fitness Gym', 'page-builder-sandwich' )
	),
	'keywords' => array( 'fitness', 'testimonials' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#f2f2f2","text":"#0d0d0d"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0d0d0d;background-color:#f2f2f2;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T1@@","name":"@@PBS_T2@@","role":"@@PBS_T3@@","rating":5} -->
<figure><blockquote><p>@@PBS_T1@@</p></blockquote><figcaption>@@PBS_T2@@, @@PBS_T3@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T4@@","name":"@@PBS_T5@@","role":"@@PBS_T3@@","rating":5} -->
<figure><blockquote><p>@@PBS_T4@@</p></blockquote><figcaption>@@PBS_T5@@, @@PBS_T3@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'What our clients say', 'page-builder-sandwich' ),
			__( 'Lost 12kg and gained a lot of confidence. The coaches are brilliant.', 'page-builder-sandwich' ),
			__( 'Rachel', 'page-builder-sandwich' ),
			__( 'Member', 'page-builder-sandwich' ),
			__( 'First gym I have stuck with for more than a month.', 'page-builder-sandwich' ),
			__( 'Sam', 'page-builder-sandwich' ),
		)
	),
);
