<?php
/**
 * Pattern "Hero" from the Fitness Gym kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Hero', 'page-builder-sandwich' ),
		__( 'Fitness Gym', 'page-builder-sandwich' )
	),
	'keywords' => array( 'fitness', 'hero' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#0d0d0d","text":"#ffffff"},"spacing":{"padding":{"top":"120px","bottom":"120px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#ffffff;background-color:#0d0d0d;padding-top:120px;padding-right:24px;padding-bottom:120px;padding-left:24px"><!-- wp:paragraph {"fontSize":"small","style":{"typography":{"textTransform":"uppercase","letterSpacing":"2px"},"color":{"text":"#ffd60a"}}} -->
<p class="has-text-color has-small-font-size" style="color:#ffd60a;letter-spacing:2px;text-transform:uppercase">@@PBS_T0@@</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">@@PBS_T1@@</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"large"} -->
<p class="has-large-font-size">@@PBS_T2@@</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"left"}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#ff3b30","text":"#ffffff"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background wp-element-button" href="/contact/" style="color:#ffffff;background-color:#ff3b30">@@PBS_T3@@</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"#ffffff"}}} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color wp-element-button" href="/services/" style="color:#ffffff">@@PBS_T4@@</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->',
		array(
			__( 'Open 5am to 11pm', 'page-builder-sandwich' ),
			__( 'Stronger every week', 'page-builder-sandwich' ),
			__( 'Coached classes, open gym and personal training for every level. Your first week is on us.', 'page-builder-sandwich' ),
			__( 'Claim a free week', 'page-builder-sandwich' ),
			__( 'See classes', 'page-builder-sandwich' ),
		)
	),
);
