<?php
/**
 * Pattern "About" from the Law Firm kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'About', 'page-builder-sandwich' ),
		__( 'Law Firm', 'page-builder-sandwich' )
	),
	'keywords' => array( 'legal', 'about' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#14213d"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#14213d;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"55%"} -->
<div class="wp-block-column" style="flex-basis:55%"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"45%"} -->
<div class="wp-block-column" style="flex-basis:45%"><!-- wp:group {"style":{"color":{"background":"#ffffff","text":"#14213d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#14213d;background-color:#ffffff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T3@@</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>@@PBS_T4@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T5@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T6@@</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>@@PBS_T7@@</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'Experienced, approachable lawyers', 'page-builder-sandwich' ),
			__( 'We are an independent firm built on long-term relationships. Many of our clients have been with us for decades.', 'page-builder-sandwich' ),
			__( 'You will always know who is handling your case, what happens next and what it will cost.', 'page-builder-sandwich' ),
			__( 'How we work', 'page-builder-sandwich' ),
			__( 'Plain-language advice', 'page-builder-sandwich' ),
			__( 'Fixed fees where possible', 'page-builder-sandwich' ),
			__( 'A named solicitor for your case', 'page-builder-sandwich' ),
			__( 'Replies within one working day', 'page-builder-sandwich' ),
		)
	),
);
