<?php
/**
 * Pattern "Call to action" from the Local Plumber kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Call to action', 'page-builder-sandwich' ),
		__( 'Local Plumber', 'page-builder-sandwich' )
	),
	'keywords' => array( 'local-services', 'cta' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#0a6cff","text":"#ffffff"},"spacing":{"padding":{"top":"72px","bottom":"72px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#ffffff;background-color:#0a6cff;padding-top:72px;padding-right:24px;padding-bottom:72px;padding-left:24px"><!-- wp:pbs/call-to-action {"title":"@@PBS_T0@@","content":"@@PBS_T1@@","primaryText":"@@PBS_T2@@","primaryUrl":"/contact/"} -->
<div><h2>@@PBS_T0@@</h2><p>@@PBS_T1@@</p><p><span><a href="/contact/">@@PBS_T2@@</a></span></p></div>
<!-- /wp:pbs/call-to-action --></div>
<!-- /wp:group -->',
		array(
			__( 'Need a plumber today?', 'page-builder-sandwich' ),
			__( 'Call now or book online. Emergency slots available around the clock.', 'page-builder-sandwich' ),
			__( 'Book a visit', 'page-builder-sandwich' ),
		)
	),
);
