<?php
/**
 * Pattern "Testimonials" from the Local Plumber kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Testimonials', 'page-builder-sandwich' ),
		__( 'Local Plumber', 'page-builder-sandwich' )
	),
	'keywords' => array( 'local-services', 'testimonials' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0b2545;background-color:#eef4ff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T1@@","name":"@@PBS_T2@@","role":"@@PBS_T3@@","rating":5} -->
<figure><blockquote><p>@@PBS_T1@@</p></blockquote><figcaption>@@PBS_T2@@, @@PBS_T3@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T4@@","name":"@@PBS_T5@@","role":"@@PBS_T3@@","rating":5} -->
<figure><blockquote><p>@@PBS_T4@@</p></blockquote><figcaption>@@PBS_T5@@, @@PBS_T3@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:pbs/testimonial {"quote":"@@PBS_T6@@","name":"@@PBS_T7@@","role":"@@PBS_T8@@","rating":5} -->
<figure><blockquote><p>@@PBS_T6@@</p></blockquote><figcaption>@@PBS_T7@@, @@PBS_T8@@</figcaption></figure>
<!-- /wp:pbs/testimonial --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'What our clients say', 'page-builder-sandwich' ),
			__( 'Came within the hour on a Sunday and fixed the leak. Brilliant.', 'page-builder-sandwich' ),
			__( 'Helen M.', 'page-builder-sandwich' ),
			__( 'Homeowner', 'page-builder-sandwich' ),
			__( 'Fair price, explained everything, left the bathroom spotless.', 'page-builder-sandwich' ),
			__( 'Tom R.', 'page-builder-sandwich' ),
			__( 'We use them for all our rental properties. Always reliable.', 'page-builder-sandwich' ),
			__( 'Aisha K.', 'page-builder-sandwich' ),
			__( 'Landlord', 'page-builder-sandwich' ),
		)
	),
);
