<?php
/**
 * Pattern "Services" from the Local Plumber kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Services', 'page-builder-sandwich' ),
		__( 'Local Plumber', 'page-builder-sandwich' )
	),
	'keywords' => array( 'local-services', 'services' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#0b2545"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0b2545;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T2@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T3@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T4@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T5@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T6@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T7@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T8@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T9@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T10@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T11@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eef4ff","text":"#0b2545"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0b2545;background-color:#eef4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T12@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T13@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'What we fix', 'page-builder-sandwich' ),
			__( 'From a dripping tap to a full bathroom, one call covers it.', 'page-builder-sandwich' ),
			__( 'Emergency repairs', 'page-builder-sandwich' ),
			__( 'Burst pipes, leaks and no water, day or night.', 'page-builder-sandwich' ),
			__( 'Boilers and heating', 'page-builder-sandwich' ),
			__( 'Servicing, repairs and new boiler installs.', 'page-builder-sandwich' ),
			__( 'Blocked drains', 'page-builder-sandwich' ),
			__( 'Sinks, toilets and outside drains cleared fast.', 'page-builder-sandwich' ),
			__( 'Bathrooms', 'page-builder-sandwich' ),
			__( 'Design, fitting and tiling, managed start to finish.', 'page-builder-sandwich' ),
			__( 'Leak detection', 'page-builder-sandwich' ),
			__( 'Hidden leaks found without tearing up the house.', 'page-builder-sandwich' ),
			__( 'Landlord checks', 'page-builder-sandwich' ),
			__( 'Safety certificates and planned maintenance.', 'page-builder-sandwich' ),
		)
	),
);
