<?php
/**
 * Pattern "Services" from the Online Academy kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Services', 'page-builder-sandwich' ),
		__( 'Online Academy', 'page-builder-sandwich' )
	),
	'keywords' => array( 'education', 'services' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#0f1b3d"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#0f1b3d;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T1@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T3@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T4@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T5@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T6@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T7@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T8@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T9@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T10@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#eff4ff","text":"#0f1b3d"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#0f1b3d;background-color:#eff4ff;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T11@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T12@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'Popular courses', 'page-builder-sandwich' ),
			__( 'Web development', 'page-builder-sandwich' ),
			__( 'HTML, CSS and JavaScript from first principles to projects.', 'page-builder-sandwich' ),
			__( 'Digital marketing', 'page-builder-sandwich' ),
			__( 'SEO, content, email and social campaigns that work.', 'page-builder-sandwich' ),
			__( 'Data analysis', 'page-builder-sandwich' ),
			__( 'Spreadsheets, SQL and dashboards for better decisions.', 'page-builder-sandwich' ),
			__( 'UX design', 'page-builder-sandwich' ),
			__( 'Research, wireframes and prototypes users love.', 'page-builder-sandwich' ),
			__( 'Project management', 'page-builder-sandwich' ),
			__( 'Plan, deliver and lead projects with confidence.', 'page-builder-sandwich' ),
			__( 'Business writing', 'page-builder-sandwich' ),
			__( 'Clear emails, reports and proposals.', 'page-builder-sandwich' ),
		)
	),
);
