<?php
/**
 * Pattern "Hero" from the Niche Authority Site kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Hero', 'page-builder-sandwich' ),
		__( 'Niche Authority Site', 'page-builder-sandwich' )
	),
	'keywords' => array( 'pbn', 'hero' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#f3f4f6","text":"#1f2937"},"spacing":{"padding":{"top":"120px","bottom":"120px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1f2937;background-color:#f3f4f6;padding-top:120px;padding-right:24px;padding-bottom:120px;padding-left:24px"><!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">@@PBS_T0@@</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"large"} -->
<p class="has-large-font-size">@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"left"}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#0f766e","text":"#ffffff"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background wp-element-button" href="/blog/" style="color:#ffffff;background-color:#0f766e">@@PBS_T2@@</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"#1f2937"}}} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color wp-element-button" href="/about/" style="color:#1f2937">@@PBS_T3@@</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->',
		array(
			__( 'Practical guides to home gardening', 'page-builder-sandwich' ),
			__( 'Straightforward advice on growing vegetables, caring for lawns and choosing the right tools, written by people who garden every weekend.', 'page-builder-sandwich' ),
			__( 'Read the latest guides', 'page-builder-sandwich' ),
			__( 'About the author', 'page-builder-sandwich' ),
		)
	),
);
