<?php
/**
 * Pattern "Features" from the Niche Authority Site kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Features', 'page-builder-sandwich' ),
		__( 'Niche Authority Site', 'page-builder-sandwich' )
	),
	'keywords' => array( 'pbn', 'features' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#1f2937"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1f2937;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:pbs/feature-list {"items":[{"title":"@@PBS_T2@@","text":"@@PBS_T3@@"},{"title":"@@PBS_T4@@","text":"@@PBS_T5@@"},{"title":"@@PBS_T6@@","text":"@@PBS_T7@@"},{"title":"@@PBS_T8@@","text":"@@PBS_T9@@"}],"columns":2,"level":3} -->
<ul><li><h3>@@PBS_T2@@</h3><p>@@PBS_T3@@</p></li><li><h3>@@PBS_T4@@</h3><p>@@PBS_T5@@</p></li><li><h3>@@PBS_T6@@</h3><p>@@PBS_T7@@</p></li><li><h3>@@PBS_T8@@</h3><p>@@PBS_T9@@</p></li></ul>
<!-- /wp:pbs/feature-list --></div>
<!-- /wp:group -->',
		array(
			__( 'Start here', 'page-builder-sandwich' ),
			__( 'The topics readers ask about most.', 'page-builder-sandwich' ),
			__( 'Growing vegetables', 'page-builder-sandwich' ),
			__( 'Raised beds, soil, sowing calendars and harvests.', 'page-builder-sandwich' ),
			__( 'Lawn care', 'page-builder-sandwich' ),
			__( 'Feeding, mowing and fixing patchy grass.', 'page-builder-sandwich' ),
			__( 'Garden tools', 'page-builder-sandwich' ),
			__( 'What is worth buying and how to look after it.', 'page-builder-sandwich' ),
			__( 'Small gardens', 'page-builder-sandwich' ),
			__( 'Balconies, patios and containers.', 'page-builder-sandwich' ),
		)
	),
);
