<?php
/**
 * Pattern "Steps" from the Estate Agency kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Steps', 'page-builder-sandwich' ),
		__( 'Estate Agency', 'page-builder-sandwich' )
	),
	'keywords' => array( 'real-estate', 'steps' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#12291a"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#12291a;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:pbs/steps {"items":[{"title":"@@PBS_T1@@","text":"@@PBS_T2@@"},{"title":"@@PBS_T3@@","text":"@@PBS_T4@@"},{"title":"@@PBS_T5@@","text":"@@PBS_T6@@"}],"layout":"horizontal","level":3} -->
<ol><li><h3>@@PBS_T1@@</h3><p>@@PBS_T2@@</p></li><li><h3>@@PBS_T3@@</h3><p>@@PBS_T4@@</p></li><li><h3>@@PBS_T5@@</h3><p>@@PBS_T6@@</p></li></ol>
<!-- /wp:pbs/steps --></div>
<!-- /wp:group -->',
		array(
			__( 'How it works', 'page-builder-sandwich' ),
			__( 'Free valuation', 'page-builder-sandwich' ),
			__( 'An agent visits and prices your home.', 'page-builder-sandwich' ),
			__( 'Launch', 'page-builder-sandwich' ),
			__( 'Photos, floor plan and listing live within days.', 'page-builder-sandwich' ),
			__( 'Sold', 'page-builder-sandwich' ),
			__( 'We negotiate and manage the sale to completion.', 'page-builder-sandwich' ),
		)
	),
);
