<?php
/**
 * Pattern "Services" from the Bistro kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Services', 'page-builder-sandwich' ),
		__( 'Bistro', 'page-builder-sandwich' )
	),
	'keywords' => array( 'restaurant', 'services' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#1f1a17"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#1f1a17;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p>@@PBS_T1@@</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T2@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T3@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T4@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T5@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T6@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T7@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T8@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T9@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T10@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T11@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#f8f2ea","text":"#1f1a17"},"spacing":{"padding":{"top":"32px","bottom":"32px","left":"28px","right":"28px"}},"border":{"radius":"14px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-text-color has-background" style="border-radius:14px;color:#1f1a17;background-color:#f8f2ea;padding-top:32px;padding-right:28px;padding-bottom:32px;padding-left:28px"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">@@PBS_T12@@</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>@@PBS_T13@@</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->',
		array(
			__( 'From our kitchen', 'page-builder-sandwich' ),
			__( 'A short menu that changes with the seasons. Ask us about allergies: we are happy to adapt.', 'page-builder-sandwich' ),
			__( 'Small plates', 'page-builder-sandwich' ),
			__( 'Charred flatbreads, cured meats and garden vegetables to start.', 'page-builder-sandwich' ),
			__( 'From the fire', 'page-builder-sandwich' ),
			__( 'Whole fish, aged steaks and roasted vegetables from the wood oven.', 'page-builder-sandwich' ),
			__( 'Fresh pasta', 'page-builder-sandwich' ),
			__( 'Made by hand every morning, served with seasonal sauces.', 'page-builder-sandwich' ),
			__( 'Desserts', 'page-builder-sandwich' ),
			__( 'Tarts, ices and a cheese board from local makers.', 'page-builder-sandwich' ),
			__( 'Set lunch', 'page-builder-sandwich' ),
			__( 'Two or three courses at a fixed price, Tuesday to Friday.', 'page-builder-sandwich' ),
			__( 'Private dining', 'page-builder-sandwich' ),
			__( 'A private room for up to 18 guests with a tailored menu.', 'page-builder-sandwich' ),
		)
	),
);
