<?php
/**
 * Pattern "Features" from the SaaS Product kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Features', 'page-builder-sandwich' ),
		__( 'SaaS Product', 'page-builder-sandwich' )
	),
	'keywords' => array( 'saas', 'features' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#15112e"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#15112e;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:pbs/feature-list {"items":[{"title":"@@PBS_T1@@","text":"@@PBS_T2@@"},{"title":"@@PBS_T3@@","text":"@@PBS_T4@@"},{"title":"@@PBS_T5@@","text":"@@PBS_T6@@"},{"title":"@@PBS_T7@@","text":"@@PBS_T8@@"},{"title":"@@PBS_T9@@","text":"@@PBS_T10@@"},{"title":"@@PBS_T11@@","text":"@@PBS_T12@@"}],"level":3} -->
<ul><li><h3>@@PBS_T1@@</h3><p>@@PBS_T2@@</p></li><li><h3>@@PBS_T3@@</h3><p>@@PBS_T4@@</p></li><li><h3>@@PBS_T5@@</h3><p>@@PBS_T6@@</p></li><li><h3>@@PBS_T7@@</h3><p>@@PBS_T8@@</p></li><li><h3>@@PBS_T9@@</h3><p>@@PBS_T10@@</p></li><li><h3>@@PBS_T11@@</h3><p>@@PBS_T12@@</p></li></ul>
<!-- /wp:pbs/feature-list --></div>
<!-- /wp:group -->',
		array(
			__( 'Everything your team needs', 'page-builder-sandwich' ),
			__( 'Boards and timelines', 'page-builder-sandwich' ),
			__( 'Switch between kanban boards and timelines in one click.', 'page-builder-sandwich' ),
			__( 'Automations', 'page-builder-sandwich' ),
			__( 'Move tasks, assign owners and send reminders automatically.', 'page-builder-sandwich' ),
			__( 'Shared files', 'page-builder-sandwich' ),
			__( 'Keep documents next to the work they belong to.', 'page-builder-sandwich' ),
			__( 'Reports', 'page-builder-sandwich' ),
			__( 'Live dashboards for workload, progress and deadlines.', 'page-builder-sandwich' ),
			__( 'Integrations', 'page-builder-sandwich' ),
			__( 'Connect the email, chat and storage tools you already use.', 'page-builder-sandwich' ),
			__( 'Security', 'page-builder-sandwich' ),
			__( 'Single sign-on, audit logs and encrypted data.', 'page-builder-sandwich' ),
		)
	),
);
