<?php
/**
 * Pattern "Hero" from the SaaS Product kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Hero', 'page-builder-sandwich' ),
		__( 'SaaS Product', 'page-builder-sandwich' )
	),
	'keywords' => array( 'saas', 'hero' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#15112e","text":"#ffffff"},"spacing":{"padding":{"top":"120px","bottom":"120px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#ffffff;background-color:#15112e;padding-top:120px;padding-right:24px;padding-bottom:120px;padding-left:24px"><!-- wp:paragraph {"fontSize":"small","align":"center","style":{"typography":{"textTransform":"uppercase","letterSpacing":"2px"},"color":{"text":"#22c3a6"}}} -->
<p class="has-text-color has-small-font-size" style="color:#22c3a6;letter-spacing:2px;text-transform:uppercase">@@PBS_T0@@</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">@@PBS_T1@@</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"large","align":"center"} -->
<p class="has-large-font-size">@@PBS_T2@@</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#6c4cf1","text":"#ffffff"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background wp-element-button" href="/contact/" style="color:#ffffff;background-color:#6c4cf1">@@PBS_T3@@</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"#ffffff"}}} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color wp-element-button" href="/services/" style="color:#ffffff">@@PBS_T4@@</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->',
		array(
			__( '14-day free trial, no card needed', 'page-builder-sandwich' ),
			__( 'Plan projects, not spreadsheets', 'page-builder-sandwich' ),
			__( 'One workspace for tasks, deadlines and files. Your team sees what matters today, and you see progress without asking for updates.', 'page-builder-sandwich' ),
			__( 'Start free trial', 'page-builder-sandwich' ),
			__( 'See features', 'page-builder-sandwich' ),
		)
	),
);
