<?php
/**
 * Pattern "Questions and answers" from the SaaS Product kit.
 *
 * GENERATED by src/kits/__tests__/kits.test.js from wp/kits/pbs/ (PBS_WRITE_KITS=1). Do not edit.
 *
 * @package ZinnDigital\PBS
 */

namespace ZinnDigital\PBS\Cloud;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'    => sprintf(
		/* translators: 1: section name, 2: kit name */
		__( '%1$s (%2$s)', 'page-builder-sandwich' ),
		__( 'Questions and answers', 'page-builder-sandwich' ),
		__( 'SaaS Product', 'page-builder-sandwich' )
	),
	'keywords' => array( 'saas', 'faq' ),
	'content'  => Patterns::fill(
		'<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#15112e"},"spacing":{"padding":{"top":"88px","bottom":"88px","left":"24px","right":"24px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="color:#15112e;background-color:#ffffff;padding-top:88px;padding-right:24px;padding-bottom:88px;padding-left:24px"><!-- wp:heading -->
<h2 class="wp-block-heading">@@PBS_T0@@</h2>
<!-- /wp:heading -->

<!-- wp:pbs/accordion {"single":true,"faq":true} -->
<div><!-- wp:pbs/accordion-item {"title":"@@PBS_T1@@","open":true} -->
<details open><summary>@@PBS_T1@@</summary><!-- wp:paragraph -->
<p>@@PBS_T2@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T3@@"} -->
<details><summary>@@PBS_T3@@</summary><!-- wp:paragraph -->
<p>@@PBS_T4@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item -->

<!-- wp:pbs/accordion-item {"title":"@@PBS_T5@@"} -->
<details><summary>@@PBS_T5@@</summary><!-- wp:paragraph -->
<p>@@PBS_T6@@</p>
<!-- /wp:paragraph --></details>
<!-- /wp:pbs/accordion-item --></div>
<!-- /wp:pbs/accordion --></div>
<!-- /wp:group -->',
		array(
			__( 'Frequently asked questions', 'page-builder-sandwich' ),
			__( 'Is there a free plan?', 'page-builder-sandwich' ),
			__( 'Yes, free for small teams, and every paid plan starts with a 14-day trial.', 'page-builder-sandwich' ),
			__( 'Can I cancel any time?', 'page-builder-sandwich' ),
			__( 'Yes. Monthly plans can be cancelled at any time.', 'page-builder-sandwich' ),
			__( 'Where is my data stored?', 'page-builder-sandwich' ),
			__( 'In secure, encrypted data centres, with daily backups.', 'page-builder-sandwich' ),
		)
	),
);
